name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy backend to Production
        run: railway up --service backend-prod --environment production --project 458173c9-77e8-43c2-9cf0-9931396f240c
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy frontend to Production
        run: railway up --service frontend-prod --environment production --project 458173c9-77e8-43c2-9cf0-9931396f240c
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
